### ISSUE TITLE
run_test.py fails

### ISSUE THREAD

**Issue by rungitta** [yupenghe/methylpy#68]
In this file https://github.com/yupenghe/methylpy/blob/methylpy/methylpy/call_mc_se.py

Is this line supposed to be here:
```bash
open(inputf+".bai",'r')
```

When I run the run_test.py I get this error in `test_error_msg.txt`:
```bash
Traceback (most recent call last):
  File "/opt/miniconda3/envs/methylpy/lib/python3.9/site-packages/methylpy/call_mc_se.py", line 1484, in call_methylated_sites
    open(inputf+".bai",'r')
FileNotFoundError: [Errno 2] No such file or directory: 'results//se_bt_processed_reads.bam.bai'
```

I see that you can create something with BAI-format, but it doesn't seem to be done in this test. When I change this line to not have the `.bai` ending then the tests succeed.

**Comment by yupenghe** [comment]
Could you please check the version of methylpy for me? I tried running methylpy test with the latest 1.4.6 but I was not able to reproduce the error.

**Comment by rungitta** [comment]
Thank you for the quick response!

I run the 1.4.6 version. I was picking up the bowtie2 from the system and thought that it was the cause of the problem. Now I install like this:

```bash
conda create -c bioconda samtools=1.3 bowtie2  cutadapt Picard  --prefix=/home/palrosen/conda/methylpy
conda activate /home/palrosen/conda/methylpy
pip install methylpy
```

I also do the optional step here described here:
https://github.com/yupenghe/methylpy#optional-step---compile-rmscpp

However I still get this error when running the test:

```bash
python run_test.py
Tests start
Tue May  4 09:12:56 2021
Test importing methylpy module.
- importing call_mc_se: pass
- importing call_mc_pe: pass
- importing DMRfind: pass
- importing parser: pass
Check methylpy executable:pass
methylpy is successfully installed!
Check whether dependencies are available in PATH
- find bowtie: failed
- find bowtie2: found version 2.3.5.1
- find minimap2: failed
- find samtools: found version 1.3.1
- find cutadapt: found version 1.18
- find java: found version 1.8.0_152-release
Only bowtie2 is available. Skip tests for bowtie related code
Test DMRfind: failed
Test eidentify-DMR: failed
Test build-reference with bowtie2: pass
Test single-end-pipeline with bowtie2: Traceback (most recent call last):
  File "run_test.py", line 224, in <module>
    stderr=f_stderr)
  File "/home/palrosen/conda/methylpy/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['methylpy', 'single-end-pipeline', '--read-files', 'data/test_data_R1.fastq.gz', '--sample', 'se_bt2', '--path-to-output', 'results/', '--forward-ref', 'chrL/chrL_f', '--reverse-ref', 'chrL/chrL_r', '--ref-fasta', 'data/chrL.fa', '--num-procs', '1', '--aligner', 'bowtie2', '--path-to-aligner', '', '--path-to-samtools', '', '--remove-clonal', 'False', '--trim-reads', 'False', '--binom-test', 'True', '--unmethylated-control', '0.005']' returned non-zero exit status 1.
```

Output of test_error_msg.txt

https://gist.github.com/rungitta/3453c69be281363935af931605273477

**Comment by yupenghe** [comment]
Thanks. The probably is related to the samtools version. Do you mind trying to upgrade the samtools to 1.9 or higher and test again?

**Comment by rungitta** [comment]
How I install:

```bash
conda create -c bioconda samtools=1.9 bowtie2 bowtie minimap2 cutadapt Picard  --prefix=/home/palrosen/conda/methylpy
conda activate ~/conda/methylpy
pip install methylpy
```

```console
cd ~/conda/methylpy/bin
wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/wigToBigWig
chmod +x wigToBigWig
```

```console
git clone https://github.com/yupenghe/methylpy.git
cd methylpy/methylpy
g++ -O3 -l gsl -l gslcblas -o run_rms_tests.out rms.cpp
./run_rms_tests.out
cp run_rms_tests.out ~/conda/methylpy/bin/
```

```bash
wget http://neomorph.salk.edu/yupeng/share/methylpy_test.tar.gz
tar -xf methylpy_test.tar.gz
cd methylpy_test/
python run_test.py
```

Results of test:

```bash
Tests start
Thu May  6 09:16:05 2021

Test importing methylpy module.
- importing call_mc_se: pass
- importing call_mc_pe: pass
- importing DMRfind: pass
- importing parser: pass
Check methylpy executable:pass

methylpy is successfully installed!

Check whether dependencies are available in PATH
- find bowtie: found version 1.2.3
- find bowtie2: found version 2.3.5.1
- find minimap2: found version 2.17-r941
- find samtools: found version 1.9
- find cutadapt: found version 2.6
- find java: found version 1.8.0_152-release
Both bowtie and bowtie2 are available and will be tested.

Test DMRfind: failed
Test reidentify-DMR: failed

Test build-reference with bowtie: pass
Test build-reference with bowtie2: pass
Test build-reference with minimap2: pass

Test single-end-pipeline with bowtie: pass
Test single-end-pipeline with bowtie2: pass
Test single-end-pipeline with minimap2: pass

Test paired-end-pipeline with bowtie: pass
Test paired-end-pipeline with bowtie2: pass
Test paired-end-pipeline with minimap2: pass

Test quality filter for BAM file of single-end data: pass

Test call-methylation-state for single-end data: pass
Test call-methylation-state for paired-end data: pass

Test merge-allc: pass

Test filter-allc: pass

All tests are done!
Thu May  6 09:17:29 2021
The tests took 83.33 seconds!
```

Output from test_error_msg.txt

```bash
free(): double free detected in tcache 2
Running RMS tests failed.
Traceback (most recent call last):
  File "/home/palrosen/conda/methylpy/bin/methylpy", line 5, in <module>
    parse_args()
  File "/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/parser.py", line 85, in parse_args
    num_sig_tests=args.min_tests)
  File "/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/DMRfind.py", line 315, in merge_DMS_to_DMR
    convergence_diff=convergence_diff)
  File "/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/DMRfind.py", line 365, in histogram_correction_DMRfind
    f = gzip.open(rms_results,'rt')
  File "/home/palrosen/conda/methylpy/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/palrosen/conda/methylpy/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'results/DMR_P0_FBvsHT_rms_results.tsv.gz'
```

**Comment by yupenghe** [comment]
Ok. It seems that the rms test is the only thing that failed. You mentioned that you have tried this option step:
https://github.com/yupenghe/methylpy#optional-step---compile-rmscpp

What message do you get if you run the below command after that step?
```
./run_rms_tests.out
```

**Comment by yupenghe** [comment]
An alternative solution is to use docker
https://github.com/yupenghe/methylpy#use-methylpy-without-installation

**Comment by rungitta** [comment]
./run_rms_tests.out
Usage: ./rms.out <chunk files> <output file> <samples> <min_cov> <num_sims>
<num_sig_tests> <seed>


-- 
Axel Rosén, Head Engineer
Research Infrastructure Services Group, USIT
University of Oslo, Norway

**Comment by yupenghe** [comment]
Cool. It seems that you have the `run_rms_tests.out` successfully compiled. So the error in DMRfind is likely due to the recompiled `run_rms_tests.out` not being in the right folder. 

If you run just `methylpy`, we can get the working path of methylpy
```
You are using methylpy 1.4.6 version
(/XXX/YYY)
```

The error should be resolved if we copy the `run_rms_tests.out` to that directory.

**Comment by rungitta** [comment]
It's in that folder, I just moved it over and still get this. It seems like this gzip file is not created.

```bash
free(): double free detected in tcache 2
Running RMS tests failed.
Traceback (most recent call last):
  File "/home/palrosen/conda/methylpy/bin/methylpy", line 5, in <module>
    parse_args()
  File "/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/parser.py", line 85, in parse_args
    num_sig_tests=args.min_tests)
  File "/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/DMRfind.py", line 315, in merge_DMS_to_DMR
    convergence_diff=convergence_diff)
  File "/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/DMRfind.py", line 365, in histogram_correction_DMRfind
    f = gzip.open(rms_results,'rt')
  File "/home/palrosen/conda/methylpy/lib/python3.7/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/palrosen/conda/methylpy/lib/python3.7/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'results/DMR_P0_FBvsHT_rms_results.tsv.gz'
```

**Comment by rungitta** [comment]
(/home/palrosen/conda/methylpy) ***@***.*** methylpy_test]$ ls results/
|grep DMR
DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv
DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv_1_0.tsv
DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv.idx
DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv
DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv_1_0.tsv
DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv.idx
DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv
DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv_1_0.tsv
DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv.idx
DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv
DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv_1_0.tsv
DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv.idx
DMR_P0_FBvsHT_rms_results_for_1_chunk_0.tsv

**Comment by yupenghe** [comment]
Yeah, the failure of generating the gzipped file is due to an issue with the run rms test executable. Did you copy `run_rms_tests.out` to `/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/`?

What message do you get if we run the below command?
```
/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/run_rms_tests.out
```

**Comment by rungitta** [comment]
```bash
(/home/palrosen/conda/methylpy) ***@***.*** methylpy_test]$ /home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/run_rms_tests.out
Usage: ./rms.out <chunk files> <output file> <samples> <min_cov> <num_sims> <num_sig_tests> <seed>
```

**Comment by yupenghe** [comment]
Are you able to run this command without error?
```
/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/run_rms_tests.out results/DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv_1_0.tsv,results/DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv_1_0.tsv,results/DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv_1_0.tsv,results/DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv_1_0.tsv results/DMR_P0_FBvsHT_rms_results_for_1_chunk_0.tsv P0_FB_1,P0_FB_2,P0_HT_1,P0_HT_2 0 3000 100 -1
```

**Comment by rungitta** [comment]
```bash
(/home/palrosen/conda/methylpy) ***@***.*** methylpy_test]$
/home/palrosen/conda/methylpy/lib/python3.7/site-packages/methylpy/run_rms_tests.out
results/DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv_1_0.tsv,results/DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv_1_0.tsv,results/DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv_1_0.tsv,results/DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv_1_0.tsv
results/DMR_P0_FBvsHT_rms_results_for_1_chunk_0.tsv
P0_FB_1,P0_FB_2,P0_HT_1,P0_HT_2 0 3000 100 -1
free(): double free detected in tcache 2
Aborted (core dumped)
```

**Comment by yupenghe** [comment]
Are you using Ubuntu (>=16.04)? If so, the below command may help.
```
cd methylpy/methylpy/
g++ -o run_rms_tests.out rms.cpp `gsl-config --cflags —libs`
```

Otherwise, I would recommend using the docker solution
https://github.com/yupenghe/methylpy#use-methylpy-without-installation

**Comment by rungitta** [comment]
I'm using rhel8. I guess the docker solution might be the only option here. 

Otherwise it seems like this is the main culprit:

```bash
free(): double free detected in tcache 2
Aborted (core dumped)
```

**Comment by yupenghe** [comment]
Yes. That is right but docker is only needed for running DMRfind. The other functions should still work without docker.

**Comment by rungitta** [comment]
I ended up doing this with conda. Then DMRfind suddenly works.

```bash
conda create --prefix=/opt/miniconda3/envs/methylpy                                                                                                                                    
conda activate /opt/miniconda3/envs/methylpy                                                                                                                                           
conda install -y -c bioconda -c conda-forge methylpy=1.4.3=py37h41a55b7_0                                                                                                              
conda install -y -c bioconda samtools=1.9
```

**Comment by yupenghe** [comment]
Cool. Glad that you found a solution!

**Comment by plantformatics** [comment]
In case anyone has the same problem, this solution worked for me as well.

**Comment by yupenghe** [comment]
Thanks. I will add this to the installation instruction.
